apiVersion: v1
kind: ConfigMap
metadata:
  name: ipl-dhaba-config
  namespace: ipldhaba
data:
  NODE_ENV: "production"
  PORT: "3001"
  REDIS_HOST: "ipldhaba-prod-redis.internal"
  REDIS_PORT: "6379"
