/**
 * The dhaba's real menu: every dish with its Andhra name, Hindi translation,
 * counter price and the photograph that ships in `public/IPL_DHABA_ITEMS/`.
 *
 * This is the *source* of the menu, not a stand-in for one. It used to live in
 * `src/data/mockData.ts` as a browser constant, which meant the price a customer
 * was charged came from a bundle they could edit. The data itself was always
 * genuine, so it moved here rather than being deleted with the rest of the mocks:
 * the seed writes it to Postgres and every client reads it back via `GET /menu`.
 *
 * Prices are paise. Images are absolute paths Vite serves from `public/`. The one
 * item that carried a stock-photo URL rather than a real photograph has an empty
 * string, which the menu renders as a neutral tile instead of a broken image.
 */
export interface SeedMenuItem {
  name: string;
  nameHi: string | null;
  description: string;
  descriptionHi: string | null;
  /** Counter price in paise. */
  pricePaise: number;
  category: string;
  image: string;
  isVeg: boolean;
  rating: number;
  prepTimeMinutes: number;
}

export const SEED_MENU_ITEMS: SeedMenuItem[] = [
  {
    name: "Powerplay Team Feast Combo (Serves 4)",
    nameHi: "पावरप्ले टीम फीस्ट कॉम्बो (4 लोगों के लिए)",
    description: "2x Chicken Biryanis + 4x Tandoori Chicken Seekh Kebab + 4x Chilled Kulhad Lassi + Masala Fries.",
    descriptionHi: "2 बिरयानी, 4 कबाब, 4 कुल्हड़ लस्सी और मसाला फ्राइज।",
    pricePaise: 99900,
    category: "Combos",
    image: "/IPL_DHABA_ITEMS/biryani boneless.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 20,
  },
  {
    name: "Amritsari Kulhad Rabri Lassi (500ml)",
    nameHi: "अमृतसरी कुल्हड़ रबड़ी लस्सी",
    description: "Thick, chilled traditional dahi lassi topped with malai, rabri, and dry fruits served in clay kulhad.",
    descriptionHi: "मलाई और मेवे से भरपूर गाढ़ी ठंडी अमृतसरी लस्सी।",
    pricePaise: 11000,
    category: "Drinks",
    image: "",
    isVeg: true,
    rating: 4.9,
    prepTimeMinutes: 5,
  },
  {
    name: "Biriyani (Boneless)",
    nameHi: "बिरयानी (बोनलेस)",
    description: "Aromatic basmati rice layered with succulent tender boneless chicken pieces & boiled egg.",
    descriptionHi: "मुलायम बोनलेस चिकन के टुकड़ों वाली लज़ीज़ दम बिरयानी।",
    pricePaise: 25000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/biryani boneless.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 20,
  },
  {
    name: "Biriyani (Bone)",
    nameHi: "बिरयानी (बोन)",
    description: "Classic dum biryani with marinated bone-in chicken pieces & boiled egg.",
    descriptionHi: "मसालेदार बोन-इन चिकन के साथ पारंपरिक दम बिरयानी।",
    pricePaise: 22000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/chicken bone.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 18,
  },
  {
    name: "Mutton Biriyani",
    nameHi: "मटन बिरयानी",
    description: "Tender mutton meat layered with saffron basmati rice & boiled egg.",
    descriptionHi: "केसरिया बासमती चावल और लज़ीज़ मटन की दम बिरयानी।",
    pricePaise: 30000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/mutton biryani.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 22,
  },
  {
    name: "Plavu Rice",
    nameHi: "पुलाव राइस",
    description: "Basmati rice cooked with fresh veggies, ghee & whole spices.",
    descriptionHi: "ताज़ी सब्जियों और मसालों के साथ पकाया बासमती पुलाव।",
    pricePaise: 12000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/plavu rice.jpg",
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 12,
  },
  {
    name: "Egg Rice",
    nameHi: "एग राइस",
    description: "Wok tossed fluffy basmati rice with scrambled egg & veggies.",
    descriptionHi: "अंडे और सब्जियों के साथ स्वादिष्ट फ्राइड राइस।",
    pricePaise: 10000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/egg rice.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 10,
  },
  {
    name: "Chicken Rice",
    nameHi: "चिकन राइस",
    description: "Wok tossed basmati rice with shredded chicken, egg drops & spring onions.",
    descriptionHi: "चिकन, अंडे और स्प्रिंग अनियन के साथ वोक फ्राइड राइस।",
    pricePaise: 15000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/chicken fried rice - 150.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 10,
  },
  {
    name: "Zeera Rice",
    nameHi: "जीरा राइस",
    description: "Fluffy basmati rice tempered with roasted cumin seeds & ghee.",
    descriptionHi: "देसी घी और भुने जीरे की सुगंध वाला बासमती चावल।",
    pricePaise: 13000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/jeera rice.jpg",
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 8,
  },
  {
    name: "Cashew Rice",
    nameHi: "काजू राइस",
    description: "Golden roasted cashews cooked with aromatic basmati rice & ghee.",
    descriptionHi: "देसी घी और भुने काजू से भरपूर स्वादिष्ट पुलाव।",
    pricePaise: 20000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/cashew rice.jpg",
    isVeg: true,
    rating: 4.7,
    prepTimeMinutes: 12,
  },
  {
    name: "Vegetable Rice",
    nameHi: "वेजीटेबल राइस",
    description: "Fresh chopped mixed vegetables tossed with seasoned basmati rice.",
    descriptionHi: "ताज़ी हरी सब्जियों और बासमती चावल का पौष्टिक मेल।",
    pricePaise: 16000,
    category: "Biryani",
    image: "/IPL_DHABA_ITEMS/vegetable rice.jpg",
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 10,
  },
  {
    name: "Chilli Chicken",
    nameHi: "चिली चिकन",
    description: "Diced chicken tossed with capsicum, onion & dark soy chili sauce.",
    descriptionHi: "शिमला मिर्च, प्याज और सोया सॉस में टॉस किया चिकन।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chilli chicken starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 14,
  },
  {
    name: "Chicken 65",
    nameHi: "चिकन 65",
    description: "South Indian style crispy fried chicken bites tossed with ginger & curry leaves.",
    descriptionHi: "करी पत्ता और अदरक के स्वाद वाला प्रसिद्ध चिकन 65।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken 65 starter.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 12,
  },
  {
    name: "Chicken 85",
    nameHi: "चिकन 85",
    description: "Extra spicy marinated chicken starter fried with peri-peri rub.",
    descriptionHi: "पेरी-पेरी मसालों से तैयार अति-मसालेदार चिकन स्टार्टर।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken85.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Kaju Chicken Fry",
    nameHi: "काजू चिकन फ्राई",
    description: "Crispy boneless chicken tossed with fried cashews & curry leaves.",
    descriptionHi: "काजू और करी पत्ते से सजा करारा चिकन स्टार्टर।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/kaju chicken fry starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Star Chicken",
    nameHi: "स्टार चिकन",
    description: "Premium marinated chef special star chicken fried to perfection.",
    descriptionHi: "शेफ की खास रेसिपी वाला प्रीमियम स्टार चिकन स्टार्टर।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/star chicken starter.jpeg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 16,
  },
  {
    name: "Ginger Chicken",
    nameHi: "जिंजर चिकन",
    description: "Chicken pieces cooked with fresh julienned ginger & coriander.",
    descriptionHi: "ताज़े अदरक के लच्छों और मसालों में पका चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/ginger chicken.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 14,
  },
  {
    name: "Chicken Vada",
    nameHi: "चिकन वड़ा",
    description: "Crispy minced chicken patties spiced with green chilies & fennel.",
    descriptionHi: "हरी मिर्च और सौंफ के फ्लेवर वाले करारे चिकन वड़े।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken vada starter.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 10,
  },
  {
    name: "Lemon Chicken",
    nameHi: "लेमन चिकन",
    description: "Chicken pieces cooked with fresh lemon juice, pepper & butter.",
    descriptionHi: "ताज़े नींबू और काली मिर्च के चटाकेदार स्वाद वाला चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/lemon chicken starter.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 12,
  },
  {
    name: "Chicken Fry (Bone)",
    nameHi: "चिकन फ्राई (बोन)",
    description: "Pan fried spiced bone-in chicken pieces with garlic & coriander.",
    descriptionHi: "लहसुन और खड़े मसालों के साथ तवा फ्राइड बोन चिकन।",
    pricePaise: 22000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken fry bone starter.jpg",
    isVeg: false,
    rating: 4.6,
    prepTimeMinutes: 14,
  },
  {
    name: "Chicken Fry (B Less)",
    nameHi: "चिकन फ्राई (बोनालेस)",
    description: "Golden crispy boneless chicken nuggets served with mint chutney.",
    descriptionHi: "पुदीने की चटनी के साथ कुरकुरा बोनलेस चिकन फ्राई।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken fry boneless starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 12,
  },
  {
    name: "Magestic Chicken",
    nameHi: "मैजेस्टिक चिकन",
    description: "Thin fried chicken strips tossed in spicy buttermilk sauce.",
    descriptionHi: "मसालेदार छाछ और हरी मिर्च में टॉस किया मैजेस्टिक चिकन।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/magestic chicken starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Punjabi Chicken (Starter)",
    nameHi: "पंजाबी चिकन (स्टार्टर)",
    description: "Robust Punjabi spiced dry roasted chicken starter.",
    descriptionHi: "पंजाबी मसालों में भुना हुआ स्वादिष्ट ड्राई चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/punjabi chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 15,
  },
  {
    name: "R.R. Chicken",
    nameHi: "आर.आर. चिकन",
    description: "Signature RR spicy fried chicken coated with secret spice blend.",
    descriptionHi: "सीक्रेट मसालों की कोटिंग वाला स्वादिष्ट आरआर चिकन।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/rr chicken starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 14,
  },
  {
    name: "Lollipop Fry",
    nameHi: "लॉलीपॉप फ्राई",
    description: "Frenched chicken wings fried crisp, served with hot garlic dip.",
    descriptionHi: "शेजवान सॉस के साथ क्रिस्पी फ्राइड चिकन लॉलीपॉप।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/lollipop fry chicken.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    name: "Leg Peace Roast",
    nameHi: "लेग पीस रोस्ट",
    description: "Juicy chicken leg drumsticks marinated in tandoori spices.",
    descriptionHi: "दही और तंदूरी मसालों में मैरीनेटेड लेग पीस।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/leg peace roast starter.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 18,
  },
  {
    name: "Lollipop Roast",
    nameHi: "लॉलीपॉप रोस्ट",
    description: "Chicken lollipops roasted over charcoal grill with red tandoori rub.",
    descriptionHi: "कोयले की आंच पर भुना तंदूरी चिकन लॉलीपॉप।",
    pricePaise: 20000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/lollipop roast starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Pepper Chicken",
    nameHi: "पेपर चिकन",
    description: "Boneless chicken sautéed with coarsely ground black pepper.",
    descriptionHi: "कुटी काली मिर्च और करी पत्ता में भुना तीखा चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/pepper chicken starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 14,
  },
  {
    name: "Dragon Chicken",
    nameHi: "ड्रैगन चिकन",
    description: "Fried chicken strips coated with sweet chili dragon glaze & cashews.",
    descriptionHi: "स्वीट चिली ड्रैगन सॉस और काजू के साथ क्रिस्पी चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/dragon chicken starter.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Tiger Chicken",
    nameHi: "टाइगर चिकन",
    description: "Bold spiced fried chicken starter tossed in fiery chili garlic sauce.",
    descriptionHi: "चिली गार्लिक सॉस में तैयार मसालेदार टाइगर चिकन।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/chicken85.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Hydrabad Chicken (Starter)",
    nameHi: "हैदराबाद चिकन (स्टार्टर)",
    description: "Hyderabadi style dry spiced chicken fry starter.",
    descriptionHi: "हैदराबादी खड़े मसालों में फ्राई किया चिकन स्टार्टर।",
    pricePaise: 28000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/hydrabad spicy chicken curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "IPL Grilled Chicken",
    nameHi: "आईपीएल ग्रिल्ड चिकन",
    description: "Charcoal grilled spicy tender chicken cuts.",
    descriptionHi: "कोयले पर ग्रिल किया हुआ स्वादिष्ट मसालेदार चिकन।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/leg peace roast starter.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 18,
  },
  {
    name: "Bone Roast Chicken",
    nameHi: "बोन रोस्ट चिकन",
    description: "Bone-in chicken roasted on tawa with caramelized onion masala.",
    descriptionHi: "प्याज और खड़े मसालों की ग्रेवी में तवा रोस्ट बोन चिकन।",
    pricePaise: 25000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/boneless roast chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 16,
  },
  {
    name: "Prawns Curry",
    nameHi: "प्रॉन्स करी",
    description: "Fresh prawns cooked in spicy coconut milk gravy.",
    descriptionHi: "नारियल के दूध और इमली की तटीय करी में ताज़े झींगे।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/prawan curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Prawns Fry",
    nameHi: "प्रॉन्स फ्राई",
    description: "Deep fried marinated prawns served with spicy green chutney.",
    descriptionHi: "हरी चटनी के साथ कुरकुरे तले हुए मसालेदार झींगे।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/prawans fry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Prawns Chilli",
    nameHi: "प्रॉन्स चिली",
    description: "Succulent prawns tossed with capsicum, green chili & soy sauce.",
    descriptionHi: "शिमला मिर्च और हरी मिर्च में टॉस किए मसालेदार झींगे।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/prawans chilli.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 14,
  },
  {
    name: "Prawns Rost",
    nameHi: "प्रॉन्स रोस्ट",
    description: "Prawns pan roasted with caramelized onions & roasted spices.",
    descriptionHi: "भुने प्याज और खड़े मसालों के साथ तवा रोस्ट झींगे।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/prawans roast.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    name: "Prawns 65",
    nameHi: "प्रॉन्स 65",
    description: "Crispy batter fried prawns tossed in spicy curd & curry leaves.",
    descriptionHi: "दही और करी पत्ता के साथ क्रिस्पी फ्राइड झींगे।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/prawans 65.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 14,
  },
  {
    name: "Apollo Fish Roast",
    nameHi: "अपोलो फिश रोस्ट",
    description: "Tawa roasted marinated fish fillets with crushed black pepper & garlic.",
    descriptionHi: "काली मिर्च और लहसुन के साथ तवा रोस्ट की हुई फिश।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/apollo fish roast.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Apollo Fish Fry",
    nameHi: "अपोलो फिश फ्राई",
    description: "Crispy batter fried fish fillets tossed in curry leaves & green chilies.",
    descriptionHi: "करी पत्ता और हरी मिर्च के साथ क्रिस्पी फ्राइड फिश।",
    pricePaise: 30000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/apollo fish fry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    name: "IPL Special Chicken",
    nameHi: "आईपीएल स्पेशल चिकन",
    description: "Chef signature rich chicken curry cooked with aromatic secret spices.",
    descriptionHi: "शेफ की खास रेसिपी वाली लज़ीज़ स्पेशल चिकन करी।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/hydrabad spicy chicken curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 18,
  },
  {
    name: "Bullet Chicken",
    nameHi: "बुलेट चिकन",
    description: "Spicy bullet chicken gravy simmered with green chilies.",
    descriptionHi: "हरी मिर्च और गरम मसालों की तीखी बुलेट चिकन करी।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/chickenbullets.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Panjabi Chicken",
    nameHi: "पंजाबी चिकन",
    description: "Rich chicken curry prepared in traditional Punjabi dhaba style.",
    descriptionHi: "देसी मसालों और तड़के वाली सुप्रसिद्ध पंजाबी चिकन करी।",
    pricePaise: 28000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/punjabi chicken curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Chicken 555",
    nameHi: "चिकन 555",
    description: "Crispy fried chicken cooked in thick fiery red chili curry.",
    descriptionHi: "लाल मिर्च और गाढ़ी करी में पका हुआ ज़ायदेदार चिकन 555।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/chicken 555 curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Mogalai Chicken",
    nameHi: "मुग़लई चिकन",
    description: "Royal chicken curry prepared with nuts, cream & saffron.",
    descriptionHi: "केसर, मेवे और मलाई की शाही मुग़लई ग्रेवी में चिकन।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/mogalai chicken curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 20,
  },
  {
    name: "Butter Chicken",
    nameHi: "बटर चिकन",
    description: "Charcoal smoked chicken tikka in smooth tomato & butter gravy.",
    descriptionHi: "मक्खन, काजू और टमाटर की शाही ग्रेवी में तंदूरी चिकन।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/butter chicken curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    name: "Indian Chicken",
    nameHi: "इंडियन चिकन",
    description: "Classic onion-tomato gravy chicken curry cooked with garam masala.",
    descriptionHi: "प्याज, टमाटर और गरम मसाले की पारंपरिक चिकन करी।",
    pricePaise: 27000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/indian chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 15,
  },
  {
    name: "Hydarabad Spicy",
    nameHi: "हैदराबाद स्पाइसी",
    description: "Authentic Hyderabadi spice mix cooked with tender chicken.",
    descriptionHi: "हैदराबादी खड़े मसालों और नारियल के तड़के वाली चिकन करी।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/hydrabad spicy chicken curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 18,
  },
  {
    name: "Ramba Chicken",
    nameHi: "रंभा चिकन",
    description: "Special spicy red chili gravy simmered with tender chicken.",
    descriptionHi: "खास रंभा मसालों और लाल मिर्च की तीखी चिकन ग्रेवी।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/rambha chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 18,
  },
  {
    name: "Bone Kadai",
    nameHi: "बोन कढ़ाई",
    description: "Bone-in chicken simmered in wok with coarsely pounded spices.",
    descriptionHi: "कढ़ाई में तैयार शिमला मिर्च और कुटे मसालों का बोन चिकन।",
    pricePaise: 28000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/kadai chicken curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Boneless Kadai",
    nameHi: "बोनलेस कढ़ाई",
    description: "Boneless chicken cooked with diced bell peppers in kadai masala.",
    descriptionHi: "कढ़ाई मसाले और शिमला मिर्च के साथ बोनलेस चिकन करी।",
    pricePaise: 28000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/boneless kadai chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 16,
  },
  {
    name: "Nellore Chicken",
    nameHi: "नेल्लोर चिकन",
    description: "Coastal Andhra style spicy chicken curry with roasted spices.",
    descriptionHi: "नेल्लोर मसालों और भुने नारियल की चटपटी चिकन करी।",
    pricePaise: 30000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/nellore chicken curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 16,
  },
  {
    name: "Andhra Chicken",
    nameHi: "आंध्र चिकन",
    description: "Spicy Guntur chili infused gravy with tender bone-in chicken.",
    descriptionHi: "गुंटूर मिर्च के तड़के वाली मसालेदार आंध्र चिकन करी।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/andhra chicken curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 18,
  },
  {
    name: "Boneless Roast Chicken",
    nameHi: "बोनलेस रोस्ट चिकन",
    description: "Pan roasted boneless chicken simmered in rich onion masala.",
    descriptionHi: "भुने हुए मसालों और प्याज की गाढ़ी ग्रेवी में बोनलेस चिकन।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/boneless roast chicken curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 18,
  },
  {
    name: "Paneer Butter Masala",
    nameHi: "पनीर बटर मसाला",
    description: "Soft paneer cubes in rich tomato, cashew & butter gravy.",
    descriptionHi: "मक्खन, मलाई और काजू की टमाटर ग्रेवी में पनीर।",
    pricePaise: 22000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/paneer butter masala.jpg",
    isVeg: true,
    rating: 4.9,
    prepTimeMinutes: 14,
  },
  {
    name: "Dal Tamato",
    nameHi: "दाल टमाटर",
    description: "Home style lentils cooked with fresh ripe tomatoes & garlic.",
    descriptionHi: "ताज़ा टमाटरों और लहसुन के तड़के वाली दाल।",
    pricePaise: 12000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/dal tomato curry.jpg",
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 10,
  },
  {
    name: "Chana Masala",
    nameHi: "चना मसाला",
    description: "Chickpeas simmered with dried pomegranate seeds & Punjabi spices.",
    descriptionHi: "अनारदाने और पंजाबी मसालों में पके चटाकेदार छोले।",
    pricePaise: 12000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/chana masala curry.jpg",
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 12,
  },
  {
    name: "Methi Chamman",
    nameHi: "मेथी चमन",
    description: "Paneer cubes and fresh fenugreek leaves in spinach gravy.",
    descriptionHi: "हरी मेथी, पालक और पनीर की कश्मीरी स्वादिष्ट डिश।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/methi chaman curry.jpg",
    isVeg: true,
    rating: 4.7,
    prepTimeMinutes: 14,
  },
  {
    name: "Kaju Curry",
    nameHi: "काजू करी",
    description: "Whole cashews roasted in ghee and cooked in creamy tomato gravy.",
    descriptionHi: "काजू और मखमली मलाईदार टमाटर ग्रेवी में शाही डिश।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/kaju curry.jpg",
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 16,
  },
  {
    name: "Kaju Mushroom",
    nameHi: "काजू मशरूम",
    description: "Fresh button mushrooms cooked with cashews in spicy Punjabi gravy.",
    descriptionHi: "ताज़े मशरूम और काजू की मसालेदार पंजाबी करी।",
    pricePaise: 25000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/kaju mushroom curry.jpg",
    isVeg: true,
    rating: 4.7,
    prepTimeMinutes: 15,
  },
  {
    name: "Kadai Panner",
    nameHi: "कढ़ाई पनीर",
    description: "Fresh cottage cheese cubes tossed with coriander & bell peppers.",
    descriptionHi: "ताज़ा पनीर, शिमला मिर्च और कुटे धनिया-मिर्च का तड़का।",
    pricePaise: 28000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/kadai panner curry.jpg",
    isVeg: true,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    name: "Mashroom Curry",
    nameHi: "मशरूम करी",
    description: "Sliced button mushrooms simmered in spiced onion tomato gravy.",
    descriptionHi: "प्याज-टमाटर और खड़े मसालों की ग्रेवी में ताज़ा मशरूम।",
    pricePaise: 22000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/mushroom curry.jpg",
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 14,
  },
  {
    name: "Jaipur Special Curry",
    nameHi: "जयपुर स्पेशल करी",
    description: "Rich yogurt & cashew based Rajasthani style veg gravy.",
    descriptionHi: "दही और काजू की गाढ़ी ग्रेवी में जयपुरी राजशाही करी।",
    pricePaise: 23000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/jaipur special curry.jpg",
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 18,
  },
  {
    name: "Palak Panner",
    nameHi: "पालक पनीर",
    description: "Paneer cubes simmered in spiced smooth spinach purée & cream.",
    descriptionHi: "पालक की मखमली प्यूरी, मलाई और ताज़े पनीर के टुकड़े।",
    pricePaise: 18000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/palak panner curry.jpg",
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 14,
  },
  {
    name: "Dal Thadka",
    nameHi: "दाल तड़का",
    description: "Yellow arhar dal tempered with desi ghee, cumin & red chilies.",
    descriptionHi: "देसी घी, जीरे और साबुत लाल मिर्च से तड़की पीली दाल।",
    pricePaise: 10000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/dal thadaka curry.jpg",
    isVeg: true,
    rating: 4.9,
    prepTimeMinutes: 10,
  },
  {
    name: "Plain Palak",
    nameHi: "प्लेन पालक",
    description: "Healthy spinach purée tempered with burnt garlic & butter.",
    descriptionHi: "भुने हुए लहसुन और मक्खन से तड़की हरी पालक प्यूरी।",
    pricePaise: 10000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/plain palak curry.jpg",
    isVeg: true,
    rating: 4.5,
    prepTimeMinutes: 10,
  },
  {
    name: "Tamoto Curry",
    nameHi: "टमाटर करी",
    description: "Tangy ripe tomatoes cooked with mustard seeds & curry leaves.",
    descriptionHi: "राई और करी पत्ता के तड़के वाली खट्टी-मीठी टमाटर करी।",
    pricePaise: 10000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/tomato curry.jpg",
    isVeg: true,
    rating: 4.5,
    prepTimeMinutes: 10,
  },
  {
    name: "Egg Curry",
    nameHi: "एग करी",
    description: "Hard boiled eggs simmered in onion-tomato masala gravy.",
    descriptionHi: "प्याज-टमाटर की मसालेदार करी में दो उबले अंडे।",
    pricePaise: 12000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/egg curry.jpg",
    isVeg: false,
    rating: 4.6,
    prepTimeMinutes: 12,
  },
  {
    name: "Egg Keema",
    nameHi: "एग कीमा",
    description: "Finely grated boiled eggs cooked in bhuna masala gravy.",
    descriptionHi: "भूने मसालों में पकाया गया बारीक एग कीमा।",
    pricePaise: 10000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/egg keema.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 12,
  },
  {
    name: "Egg Burji",
    nameHi: "एग भुर्जी",
    description: "Scrambled eggs spiced with green chilies, onions & butter.",
    descriptionHi: "मसालेदार अंडे की भुर्जी मक्खन और चटपटे प्याज के साथ।",
    pricePaise: 10000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/egg burji curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 10,
  },
  {
    name: "Egg Fry",
    nameHi: "एग फ्राई",
    description: "Pan roasted whole boiled eggs in thick spicy dhaba masala.",
    descriptionHi: "मसाले में भुने उबले अंडे और लजीज गाढ़ी ग्रेवी।",
    pricePaise: 15000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/egg fry curry.jpg",
    isVeg: false,
    rating: 4.7,
    prepTimeMinutes: 12,
  },
  {
    name: "Egg Thadka",
    nameHi: "एग तड़का",
    description: "Boiled eggs in double-tempered yellow lentils & aromatic spices.",
    descriptionHi: "स्वादिष्ट तड़का दाल में उबले अंडे और देसी मसाले।",
    pricePaise: 13000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/Egg Tadka curry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 15,
  },
  {
    name: "Egg Palak",
    nameHi: "एग पालक",
    description: "Boiled eggs cooked in healthy smooth spinach purée.",
    descriptionHi: "ताज़ा पालक की प्यूरी और मसालों में उबले अंडे।",
    pricePaise: 13000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/egg palak curry.jpg",
    isVeg: false,
    rating: 4.6,
    prepTimeMinutes: 14,
  },
  {
    name: "Mutton Curry",
    nameHi: "मटन करी",
    description: "Slow cooked mutton on bone in rustic dhaba style gravy.",
    descriptionHi: "देसी तपेले में धीमी आंच पर पकी मटन मसाला करी।",
    pricePaise: 35000,
    category: "Curries",
    image: "/IPL_DHABA_ITEMS/mutton curry.jpg",
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 20,
  },
  {
    name: "Mutton Fry",
    nameHi: "मटन फ्राई",
    description: "Pan roasted tender mutton pieces with cracked pepper & curry leaves.",
    descriptionHi: "करी पत्ता और कुटी काली मिर्च के साथ भुना सुक्का मटन।",
    pricePaise: 35000,
    category: "Starters",
    image: "/IPL_DHABA_ITEMS/mutton fry.jpg",
    isVeg: false,
    rating: 4.8,
    prepTimeMinutes: 18,
  },
  {
    name: "Pulka",
    nameHi: "फुल्का",
    description: "Whole wheat soft puffed phulka cooked over open flame.",
    descriptionHi: "गेहूं का मुलायम तवा फुल्का।",
    pricePaise: 1000,
    category: "Breads",
    image: "/IPL_DHABA_ITEMS/pulka.jpg",
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 5,
  },
];
